version: "3.9"

x-common: &common
  env_file:
    - .env
  stdin_open: true
  tty: true
  environment:
    - "POSTGRES_USER=postgres"
    - "POSTGRES_PASSWORD=password"
    - "RAILS_ENV=development"

services:
  db:
    <<: *common
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_POSTGRES_CPUS:-0}"
          memory: "${DOCKER_POSTGRES_MEMORY:-0}"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "3s"
    image: "postgres:16.2"
    volumes:
      - "myl-postgres-data:/var/lib/postgresql/data"
  app:
    <<: *common
    build:
      context: .
    command: bash -c "./bin/dev"
    volumes:
      - .:/myl-deck-builder
      - gems:/gems
      - node_modules:/app/node_modules
    ports:
      - "3004:3004"
    depends_on:
      - db
volumes:
  myl-postgres-data:
    driver: local
  gems:
    driver: local
  node_modules:
    driver: local
